### PR TITLE
LPD-16391 The downloadBundle task will fail when the release server is unavailable even when the file is already downloaded

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPD-16391](https://https://liferay.atlassian.net/browse/LPD-16391).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
@gamerson would you be willing to give this one a review?

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
@simonjhy I went ahead and removed that src=dest check completely.

**Comment by drewbrokke** [comment]
@gamerson would you be willing to give this one a quick look? I have no idea how I'd even get the exception I removed to throw now that the task skips when the bundle is present on the filesystem.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Review by gamerson — COMMENTED** [review]
One quick question.  What about verification? 

So I understand that if the cache dir has the file and the release server is not available, this will just use the cache version.

But what if the cached file is available, and the release server "is" available, will having the cache version of the file cause it to not "verify" the md5sum for the file? 

Just wanted to make sure that the "verification" is only "skipped" if the release server is not online.

**Comment by gamerson** [comment]
> @gamerson would you be willing to give this one a quick look? I have no idea how I'd even get the exception I removed to throw now that the task skips when the bundle is present on the filesystem.

It seems like you could still have a `src!=dest` check right? Maybe I'm not thinking of something here, but the check for "if the file already exist" could be separate from the "check if src != dest"?   Ping me today online and we can chat about it.

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:report:2536554042

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:report:2536688377

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward:force

**Comment by drewbrokke** [comment]
ci:forward:force

**Pull request closed without merging**
