### PR TITLE
Nicolas - SF Automation - Master LPD-35582 

### PR DESCRIPTION
**Pull request by rubenssoares-br**
Ticket - https://liferay.atlassian.net/browse/LPD-35582
@nicolas-sss

### CODE REVIEW

**Comment by rubenssoares-br** [comment]
ci:test:sf

**Comment by rubenssoares-br** [comment]
ci:test:hotel

**Comment by rubenssoares-br** [comment]
ci:test:sf

**Comment by rubenssoares-br** [comment]
ci:test:hotel

**Review by nicolas-sss — APPROVED** [review]

**Comment by nicolas-sss** [comment]
@rubenssoares-br since it's been so long, remember the workflow, rebase, and rerun the tests (at least locally) before forwarding.
Something someone else might have added could change the order of something you've added in those files.
 ;)

**Comment by rubenssoares-br** [comment]
ci:test:sf

**Comment by rubenssoares-br** [comment]
ci:test:hotel

**Comment by rubenssoares-br** [comment]
PR sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/154019

**Pull request closed without merging**
