### PR TITLE
LPD-37518 Add "scope" field to the "GlobalCSSCET" and validate it at build time

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Sending here from https://github.com/liferay-platform-experience/liferay-portal/pull/836.

@drewbrokke this one is similar to what I did for the GlobalJS CX. It's just scoping it to the company level.

# Original description

https://liferay.atlassian.net/browse/LPD-37518

## Goal
Scope the GlobalCSSCET to the instance (company) level

## Approach

- Add the `scope` field to `GlobalCSSCET.java`
- Field validation performed at build time in `ClientExtensionProjectConfigurator.java`
- Put this feature behind the epic’s feature flag https://liferay.atlassian.net/browse/LPD-36701 

## Up next
Next PR will be injecting the GlobalCSSCET into the page. The ticket will be https://liferay.atlassian.net/browse/LPD-37520

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:gradle-plugins

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
LGTM, thanks @thiago-buarqque! Let's see if we can get `gradle-plugins` passing. 

Also, is everything working properly in the CX samples?

**Comment by thiago-buarqque** [comment]
ci:test:gradle-plugins

**Comment by thiago-buarqque** [comment]
@drewbrokke  What do you mean by "Is everything working properly in the CX samples?"

There isn't an official sample for this one yet, I just have it in my local, it's working fine

**Comment by drewbrokke** [comment]
@thiago-buarqque that works for me - just double-checking to make sure that the samples have been at least locally tested.

**Comment by thiago-buarqque** [comment]
ci:test:gradle-plugins

**Comment by thiago-buarqque** [comment]
@drewbrokke The gradle-plugins suite is flaky, I check [its history](https://testray.liferay.com/#/project/35392/routines/45357/build/87884114/case-result/87896277/history). I have looked at the logs and I don't see errors related to the test I added, neither others related to CXs. May I forward this one?

**Comment by drewbrokke** [comment]
@thiago-buarqque yes I agree, go ahead and forward. Thank you for checking.

**Comment by thiago-buarqque** [comment]
ci:forward

**Pull request closed without merging**
