### PR TITLE
LPS-203589 Use of library with known vulnerability: Spring Boot 2.7.11 (workspaces)

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Review by drewbrokke — CHANGES_REQUESTED** [review]
Thanks for sending this, @Seiphon. Looks like there are a few more places to check:

- [ ] workspaces/liferay-sample-workspace/client-extensions/liferay-sample-etc-spring-boot/build.gradle
- [ ] workspaces/liferay-jethr0-workspace/client-extensions/liferay-jethr0-etc-spring-boot/build.gradle
- [ ] workspaces/liferay-evp-workspace/client-extensions/liferay-evp-etc-spring-boot/build.gradle
- [ ] workspaces/liferay-customer-workspace/client-extensions/liferay-customer-etc-spring-boot/build.gradle
- [ ] workspaces/liferay-clarity-workspace/client-extensions/liferay-clarity-etc-spring-boot/build.gradle
- [ ] workspaces/liferay-ticket-workspace/client-extensions/liferay-ticket-etc-spring-boot/build.gradle
- [ ] workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-etc-spring-boot/build.gradle
- [ ] modules/util/client-extension-util-spring-boot/build.gradle
- [ ] modules/sdk/gradle-plugins-defaults/build.gradle

**Comment by Seiphon** [comment]
> Thanks for sending this, @Seiphon. Looks like there are a few more places to check:
> 
> * [ ]  workspaces/liferay-sample-workspace/client-extensions/liferay-sample-etc-spring-boot/build.gradle
> * [ ]  workspaces/liferay-jethr0-workspace/client-extensions/liferay-jethr0-etc-spring-boot/build.gradle
> * [ ]  workspaces/liferay-evp-workspace/client-extensions/liferay-evp-etc-spring-boot/build.gradle
> * [ ]  workspaces/liferay-customer-workspace/client-extensions/liferay-customer-etc-spring-boot/build.gradle
> * [ ]  workspaces/liferay-clarity-workspace/client-extensions/liferay-clarity-etc-spring-boot/build.gradle
> * [ ]  workspaces/liferay-ticket-workspace/client-extensions/liferay-ticket-etc-spring-boot/build.gradle
> * [ ]  workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-etc-spring-boot/build.gradle
> * [ ]  modules/util/client-extension-util-spring-boot/build.gradle
> * [ ]  modules/sdk/gradle-plugins-defaults/build.gradle

Hey @drewbrokke, I noticed there are Spring Boot dependencies on these places, but actually there are knewn vulnerability only in the "org.springframework.boot: spring-boot: 2.7.11". For "spring-boot-starter-web", "spring-boot-starter-activemq", "spring-boot-starter-webflux" and "spring-boot-starter-oauth2-resource-server", they don't have the vulnerability issues one their "2.7.11" version, so I need to comfirm, is that neccessary to upgrade them all?

**Comment by drewbrokke** [comment]
> is that neccessary to upgrade them all?
@Seiphon good question. I suppose it is not strictly necessary. However, I'd want to know if there are reasons _not_ to upgrade the corresponding libs. Is there a downside?

**Comment by Seiphon** [comment]
> > is that neccessary to upgrade them all?
> > @Seiphon good question. I suppose it is not strictly necessary. However, I'd want to know if there are reasons _not_ to upgrade the corresponding libs. Is there a downside?

@drewbrokke , I believe there is no downside, I have tried to upgrade them all, and there is no compile issue, so I think it would be fine to upgrade them all. I resent the pr here https://github.com/liferay-devtools/liferay-portal/pull/4 thanks!

**Pull request closed without merging**
