### PR TITLE
 LPS-193787 dynamic get latest node and npm version

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
@simonjhy an update on this one, I am playing around with it locally. I may want to adjust the extension api a bit, I'm not certain that `useLatestNode` is necessarily what we want. We may also want to support declaring a specific LTS version (Iron, Hydrogen, Gallium, ect...). I'll keep looking at it tomorrow.

**Comment by drewbrokke** [comment]
See https://github.com/liferay-devtools/liferay-portal/pull/9

**Pull request closed without merging**
