### PR TITLE
LPD-26470 Fix Poshi syntax issues

### PR DESCRIPTION
**Pull request by CalumR23**
@ling-alan-huang 
cc: @drewbrokke 
Hey guys I made some changes to get around the syntax issues mentioned here:
https://github.com/liferay-devtools/liferay-portal/pull/91#issue-2333141307

### CODE REVIEW

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:test:stable

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
Thank you @CalumR23

**Comment by ling-alan-huang** [comment]
Thank you @CalumR23 Forwarding https://github.com/liferay-devtools/liferay-portal/pull/96

**Pull request closed without merging**
