### PR TITLE
LPD-31137 Work for FragmentCollectionContributor service needs to add property fragment.collection.key in the @Component

### PR DESCRIPTION
**Pull request by ling-alan-huang**
> https://liferay.atlassian.net/browse/LPD-31137
> Passed automation testing and review
> https://github.com/liferay-devtools/liferay-portal/pull/129
> 
> @ling-alan-huang Brian Chan asked you to take a look at this here: https://github.com/brianchandotcom/liferay-portal/pull/152471#issuecomment-2237772532 I'm not sure if its because too many PRs were creating _joinLines as a helper function or if there is a pre-existing better way to do it? This PR is needed though to refactor previous uses to just use the inherited helper function for it instead of recreating it for multiple test rule checks

/cc @drewbrokke @kyle-miho

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:hotel

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:stable

**Comment by kyle-miho** [comment]
@ling-alan-huang relevant/stable failures seem to be unrelated

**Comment by kyle-miho** [comment]
ci:test:stable

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
