### PR TITLE
master lpd 29804

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-29804

cc: @drewbrokke @nicolas-sss

Currently the upgrade does not add an import of the newly added Model class, but I did not add it because it doesnt seem like a way to guarantee finding the correct import path of the model. I think its safer to let the compile fail and let the user add the import itself? Or is there a good way to add the missing model path

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:hotel

**Comment by kyle-miho** [comment]
We can probably best get the package name through the service.xml

**Comment by kyle-miho** [comment]
JavaSourceUtil or a normal gw formatSource will fix the missing import. We technically cant easily and guaranteed find the Model package path since this upgrade can occur in any module (ive seen it occur in -web, -service and -impl)

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@kyle-miho in regards to the import of the model, is it not sufficient to use the `ContributorConstants.ENTRY_CLASS_NAME_PROPERTY_KEY` property value found on the left side of the diff [here](https://github.com/drewbrokke/liferay-portal/commit/e53e3eb6e5fec9b36f31b5c79e7067c26c4432fb), for example?

**Comment by kyle-miho** [comment]
@drewbrokke Ohhhh thanks, the ticket is technically incorrect in what needs to be fixed then, thanks for the catch. i didnt realize the component annotation is supposed to be updated with it as well as it having the package info for the model. Got it, ill fix this!

**Pull request closed without merging**
