### PR TITLE
LPD-30273 Investigate Project Templates Test Failures

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPD-30273](https://liferay.atlassian.net/browse/LPD-30273).

@kyle-miho I was poking around a bit and figured I'd submit what I've found so far. Take a look when you have a chance.

@petershin would you be willing to validate this solution? Is there a better or more idiomatic way to do this?

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:project-templates

**Comment by drewbrokke** [comment]
ci:test:project-templates

**Comment by kyle-miho** [comment]
@drewbrokke the error is still happening in project-templates-portlet-toolbar-contributor for some reason even though you already fixed it. I'll check the most recent results from the suite to double check
https://testray.liferay.com/#/project/34754/routines/34756/build/37228333/case-result/37230536

**Comment by drewbrokke** [comment]
ci:test:blade

**Comment by kyle-miho** [comment]
ci:help

**Comment by petershin** [comment]
See https://github.com/liferay-devtools/liferay-portal/pull/134

**Pull request closed without merging**
