### PR TITLE
master lpd 27000

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-27000

Unit tests pass locally as well.

cc: @drewbrokke @nicolas-sss

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

@nicolas-sss does this look ok to you?

**Comment by nicolas-sss** [comment]
ci:test:hotel

**Comment by nicolas-sss** [comment]
LGTM 👍

For the next few, it's not necessary to add each new import added to imports.txt to the test file. It's a redundant test unless the import is testing some specific logic in the code, the ones already in the test file test the check functionality as a whole. ;)

@kyle-miho  Cc @drewbrokke

**Comment by kyle-miho** [comment]
ci:forward

**Pull request closed without merging**
