### PR TITLE
LPD-39620 Update the commerceCheckoutStep samples and CX library to be able to serve static resources

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianikim** [comment]
@rotty3000 , we need same implementation for `liferay-paypal-workspace` checkout step: https://github.com/liferay-devtools/liferay-portal/tree/master/workspaces/liferay-paypal-workspace/client-extensions/liferay-paypal-commerce-checkout-step

**Comment by rotty3000** [comment]
@brianikim @drewbrokke I feel that you guys are well equipped to propagate this change wherever you need at this point. You can either push more directly to this PR branch or merge it and duplicate the changes in other locations.

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
Looks fine to me @rotty3000. @brianikim any more you think needs to be added to this particular pull, or can further changes come in other PRs?

**Comment by brianikim** [comment]
https://github.com/liferay-devtools/liferay-portal/pull/308

**Comment by brianikim** [comment]
ci:close

**Pull request closed without merging**
