### PR TITLE
Nicolas - SF Automation - master lpd 27841

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-27841
@nicolas-sss this is the fourth PR to review

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:hotel

**Review by nicolas-sss — APPROVED** [review]

**Comment by nicolas-sss** [comment]
Manually forwarded [here](https://github.com/brianchandotcom/liferay-portal/pull/153899)

**Comment by nicolas-sss** [comment]
@kyle-miho feel free to close this ticket, thx.

**Pull request closed without merging**
