### PR TITLE
LPD-5499 Turn on target platform gradle-plugins tests

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPD-5499](https://liferay.atlassian.net/browse/LPD-5499).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by kyle-miho** [comment]
Testing if SF checks are broken at head

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Pull request closed without merging**
