### PR TITLE
LPD-6610 [BE] Update Dev Tools to provide support for adding a frontend-token-definition.json to the Theme CSS CX in a Liferay Workspace

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPD-6610](https://liferay.atlassian.net/browse/LPD-6610).
This is an update for [LPD-7009](https://liferay.atlassian.net/browse/LPD-7009).
This is an update for [LPD-20533](https://liferay.atlassian.net/browse/LPD-20533).

@ethib137 @thiago-buarqque @algobob @izaera

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
Hey @drewbrokke, this PR is missing the commits from #38

**Comment by thiago-buarqque** [comment]
The #38 and #39 are related, #38 comes before #39 in commit history

**Comment by drewbrokke** [comment]
So it's two separate PRs under the same ticket? Sorry I got confused by that. Any reason they are not a single pull?

**Comment by thiago-buarqque** [comment]
@drewbrokke  We just wanted to make sure the PR was small enough so Brian would complain about the size of it (we had some events recently hahah)

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:report

**Comment by drewbrokke** [comment]
ci:report:2554094910

**Comment by drewbrokke** [comment]
ci:forward:force

**Comment by drewbrokke** [comment]
The client extension samples failures are due to an unrelated issue in the workspaces when run using Gradle 8.

**Pull request closed without merging**
