### PR TITLE
Nicolas - SF Automation - Master LPD-36114

### PR DESCRIPTION
**Pull request by MicaelleSilvaa**
Ticket: https://liferay.atlassian.net/browse/LPD-36114

**ModelResourcePermissionHelper** Replaced in: https://github.com/liferay/liferay-portal/commit/18053bdaa6dcf4ed423dbca4fb81db722db68e9b

### CODE REVIEW

**Comment by MicaelleSilvaa** [comment]
@nicolas-sss

**Comment by MicaelleSilvaa** [comment]
ci:test:sf

**Review by nicolas-sss — APPROVED** [review]

**Comment by nicolas-sss** [comment]
ci:test:sf

**Comment by MicaelleSilvaa** [comment]
forward to brian: https://github.com/brianchandotcom/liferay-portal/pull/154110

**Pull request closed without merging**
