### PR TITLE
LPS-205232 restore css builder version and update service builder tool version for project template

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:project-templates

**Review by drewbrokke — APPROVED** [review]
Thanks @simonjhy!

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@simonjhy I think those are real test failures. Can you please investigate? Thanks!

**Review by drewbrokke — COMMENTED** [review]
Changing to "Request changes" for now.

**Review by drewbrokke — CHANGES_REQUESTED** [review]
Changing to "Request changes" for now.

**Comment by simonjhy** [comment]
> @simonjhy I think those are real test failures. Can you please investigate? Thanks!

OK

**Pull request closed without merging**
