### PR TITLE
LPD-43551 Add company scoped global CSS sample and functional test

### PR DESCRIPTION
**Pull request by thiago-buarqque**
@drewbrokke sending here to speed things up, once https://github.com/liferay-devtools/liferay-portal/pull/315 is merged, I run CI for this one and forward it in case everything is good

## Goal

Add the sample and the functional test for company scoped Global CSS CXs.

## Approach

I have updated the existing sample to be numbered as the first one, mine will be second

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:playwright

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:playwright

**Review by drewbrokke — APPROVED** [review]

**Comment by thiago-buarqque** [comment]
ci:forward:force

**Pull request closed without merging**
