### PR TITLE
LPD-23186 Add AssertFailCheck and EqualsHashCodeCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://liferay.atlassian.net/browse/LPD-23186

@ealonso Please send a follow-up PR to remove `AssertFailJUnitRule` and `OverrideBothEqualsAndHashcodeRule` from PMD when this PR is merged. Thanks.

/cc @drewbrokke @liferay-devtools

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@drewbrokke Sorry, I already forwarded, I forgot to ask you that should every SF PR need your review?

**Comment by drewbrokke** [comment]
Hi @ling-alan-huang, thanks for asking. No I don't think I need to review every pull. It is enough to see it here :). Also, there is no need to mention the @liferay-devtools user.

Thank you for sending here!

**Pull request closed without merging**
