### PR TITLE
LPD-36494 add playwright test to the language client extension

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Resending from https://github.com/brianchandotcom/liferay-portal/pull/155315 after requests from Brian.

1. Last week Brian asked to revert https://github.com/liferay-devtools/liferay-portal/commit/7fc15924b3823360a2fc564a5b6b173eb3c7d647. See why I did that in the description [here](https://github.com/liferay-platform-experience/liferay-portal/pull/754). Now he agreed to go with my approach.

2. He asked to make the batch import work using the import strategy approach of `ON_ERROR_CONTINUE`. But the batch engine seems to have a bug. I opened a thread [here](https://liferay.slack.com/archives/C5E1CRLJY/p1729705799288129).

    - Fixed the issue and the changes were approved by @4lejandrito [here](https://github.com/liferay-devtools/liferay-portal/pull/280#issuecomment-2435538070)

cc: @ethib137

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:gradle-plugins

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Review by ethib137 — APPROVED** [review]
LGTM

**Comment by 4lejandrito** [comment]
@thiago-buarqque changes on batch look good. Go forward.

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:gradle-plugins

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:forward:force

**Pull request closed without merging**
