### PR TITLE
LPD-27995 Allow variable names to be anything as long as the className is correctly matched to account for client solutions

### PR DESCRIPTION
**Pull request by kyle-miho**
@drewbrokke @nicolas-sss Follow up from concern Nicolas raised earlier. Variable names need to never be enforced, we use className to enforce that the variable type is correct if we need to use a reference since client solutions can technically use any variable name and not just our SF standards. I also added a case to test for this to make sure this is covered for anyone else that may work on this project and not know the reason why

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:hotel

**Review by drewbrokke — COMMENTED** [review]
@kyle-miho does this not have the possibility to clobber other unrelated classes that happen to have methods with the same signature? Wouldn't it be better to _not_ upgrade something then _force_ something to be upgraded that shouldn't be?

**Comment by kyle-miho** [comment]
@drewbrokke adding the className is supposed to verify this, but it doesnt seem to be working with regexes for some reason. Im adding a test for this and am debugging it now

**Pull request closed without merging**
