### PR TITLE
LPD-7009 Read and validate script element attributes from .yaml file for deployed client extension

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPD-7009](https://liferay.atlassian.net/browse/LPD-7009).

@thiago-buarqque @ethib137 see https://github.com/liferay-devtools/liferay-portal/pull/42/commits/190f8f6e2bf7b7fc7da64ff91ff74da161ef521d

FYI @petershin

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@ethib137 if this looks good to you feel free to forward, otherwise lmk if you have any further questions or concerns.

**Comment by ethib137** [comment]
LGTM. Thanks.

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
