### PR TITLE
LPD-36494 Convert properties files from the /language folder to a batch client extension at build time

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPD-36494](https://liferay.atlassian.net/browse/LPD-36494).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
Hey @drewbrokke, I was off yesterday. Thanks for making the changes, it was definitely faster. 

Everything seems to be working fine. I am now requesting @ethib137's review.

Do we have to keep those "FAKE GRADLE CACHE" commits?

**Comment by drewbrokke** [comment]
@thiago-buarqque no they are only needed for testing the PR.

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
Resent to https://github.com/liferay-devtools/liferay-portal/pull/259

**Comment by thiago-buarqque** [comment]
ci:close

**Pull request closed without merging**
