### PR TITLE
LPS-202509 Dev Workspace: Add a substitution variable containing the build time that can be used in CX URLs

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
seems there is a different desire for how this is actually implemented.

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Plugins failures are present on other pulls. Forwarding.

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
