### PR TITLE
master lpd 40131

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-40131
https://liferay.atlassian.net/browse/LPP-56189

- **LPD-40131 Revert "LPD-21814 gradle-plugins-workspace: fixes jsPortlet test failure"**
- **FAKE-GRADLE-CACHE**

Temporarily leaving in FAKE-GRADLE-CACHE for convenience. Tested locally on 12.1.1 and this fixes the customer issue. Running tests on CI to find where the potential test failure fix is located

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:help

**Comment by kyle-miho** [comment]
ci:test:dev-tools

**Comment by kyle-miho** [comment]
ci:test:gradle-plugins

**Comment by kyle-miho** [comment]
ci:report

**Comment by kyle-miho** [comment]
ci:report:50400242

**Comment by kyle-miho** [comment]
ci:test:dev-tools

**Comment by kyle-miho** [comment]
@drewbrokke can you take a look at the test fix? This fixes the jsPortlet failure in gradleTest for gradle-plugins-workspace. I'm not sure if I fixed it the best possible way, but worst case I think we should at least aim to try and merge the revert asap and then add the test fix afterwards so we can close the lpp

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@kyle-miho I think we should have two goals with this fix:
- Add a new test case to illustrate the issue presented in [LPD-40131](https://issues.liferay.com/browse/LPD-40131)
- Leave the original test case unchanged
I want to exhaust our options before going this route. If you have to change the test case, someone out there will have to change their code after this "fix" breaks it.

**Comment by kyle-miho** [comment]
https://github.com/liferay-devtools/liferay-portal/pull/287

**Pull request closed without merging**
