### PR TITLE
master lpd 26999

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-26999

cc: @drewbrokke @ling-alan-huang @nicolas-sss

This should cover 2 main cases for both the bnd.bnd and service.xml, updating the expected value if -ds-annotations or dependency-injector was already set for a customer, and if not we need to add the value as well.

I used a regex to replace the XML content instead of modifying the XML document object directly due to the differences in how XML files are normally created and Liferay's SF Standards for xml files. This seems the safest to do for customers considering I dont know their SF standards in their service.xml files which is also why I used a generous regex as well to allow whitespaces.

Not sure if I missed anything, esp for any SF standards since this is the creation of a new file instead of just updating one. Everything appears to work though! I tested with unit tests before/after development so it seems like it works to me.

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by nicolas-sss** [comment]
ci:test:hotel

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by nicolas-sss** [comment]
LGTM 👍

Please run the SF and hotel CI suites.

**Comment by ling-alan-huang** [comment]
@kyle-miho Please check my changes https://github.com/liferay-devtools/liferay-portal/pull/81

**Pull request closed without merging**
