### PR TITLE
LPD-31151 Check test.properties for Playwright test

### PR DESCRIPTION
**Pull request by ling-alan-huang**
/cc @sandrodw3

https://liferay.atlassian.net/browse/LPD-31151

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:forword

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ealonso** [comment]
@ling-alan-huang I think tests failures are not related with your changes

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
