### PR TITLE
LPD-26805 Remove nonexistent paths

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
Hey @drewbrokke Do the test failures relate to my changes? Do we have any test engineer can help with this PR?

**Comment by drewbrokke** [comment]
Hey @ling-alan-huang, I think those are real failures, but only because your pull allowed those tests to run whereas they probably were not running at all before, so the failures were being masked. I'll ask around to see if someone can assist you with fixing them.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by CalumR23** [comment]
Hey @ling-alan-huang @drewbrokke I checked this out and saw that these are just "empty" poshi files. Theres two ways to fix this.

1. You can add echos into them so they have some content
2. You can just delete the two offending files since it looks like they were created for a new test but since the switch to Playwright, they were never written

**Comment by drewbrokke** [comment]
FYI @ryanschuhler please see Calum's comment above.

**Comment by ryanschuhler** [comment]
removed the empty tests here https://github.com/brianchandotcom/liferay-portal/pull/150972

**Comment by ling-alan-huang** [comment]
Thanks @CalumR23 I don't understand your option 1.
But looks like @ryanschuhler aready done option 2. I will forward when it's merged.
Thank you guys.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
