### PR TITLE
master lpd 32470

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-32470
@drewbrokke @petershin

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:dev-tools

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:report:53797548

**Comment by drewbrokke** [comment]
ci:test:devtools

**Comment by drewbrokke** [comment]
ci:test:dev-tools

**Comment by kyle-miho** [comment]
ci:test:dev-tools

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@drewbrokke We can isolate this fix to JDK8, and add a follow up to JDK21 seperately if need be? But it fixes the 3 test suites there and offers no further regressions, its only still failing on JDK17 which should be removed once it gets merged https://testray.liferay.com/#/project/34754/routines/34756/build/60123088?filter=%7B%22testrayRunId%22%3A%5B60144326%5D%7D&filterSchema=buildResults

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
@kyle-miho a fix for the `gradle-plugins` failures is in Brian's queue here: https://github.com/brianchandotcom/liferay-portal/pull/153328

**Comment by kyle-miho** [comment]
ci:test:gradle-plugins

**Comment by kyle-miho** [comment]
ci:forward

**Pull request closed without merging**
