### PR TITLE
LPD-31541 update com.fasterxml.jackson.dataformat:jackson-dataformat-yaml to 2.16.1

### PR DESCRIPTION
**Pull request by annasuszter**

### CODE REVIEW

**Comment by annasuszter** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:help

**Comment by annasuszter** [comment]
ci:help

**Comment by annasuszter** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by annasuszter** [comment]
ci:test:sf

**Comment by annasuszter** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:workspaces

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
LGTM, thanks @annasuszter!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
FYI the failure on the `workspaces` suite is a known failure since that one workspace requires JDK11+, but the tests are run on JDK8.

**Pull request closed without merging**
