### PR TITLE
LPD-29513 [portal] add support for local deployment of CX bundles to different virtual instances

### PR DESCRIPTION
**Pull request by annasuszter**
cc @drewbrokke

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
https://github.com/liferay-devtools/liferay-portal/pull/142

**Review by drewbrokke — COMMENTED** [review]
This is looking good, @annasuszter. I went ahead and made a number of changes, but I tried to keep them broken up so you can see the reasoning behind each one. We can go over the new pull tomorrow.

**Comment by annasuszter** [comment]
New PR: #148

**Pull request closed without merging**
