### PR TITLE
LPD-16079 Workspace cannot be used if .product_info.json is unavailable on the network

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPD-16079](https://issues.liferay.com/browse/LPD-16079).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Review by gamerson — APPROVED** [review]
LGTM!

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by holatuwol** [comment]
How does this detect changes to `.product_info.json`?

I don't see anything that deletes it automatically if the specified product version is missing from the downloaded file. Will people be instructed to delete that file to get it to refresh when they change their workspace version?

**Comment by drewbrokke** [comment]
So far the change detection happens internally with the `DownloadCommand`. It will compare the modified time headers and re-fetch if they are different.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Review by drewbrokke — COMMENTED** [review]
ci:forward

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
