### PR TITLE
LPD-37520 Import "company" scoped Global CSS CX

### PR DESCRIPTION
**Pull request by thiago-buarqque**
@drewbrokke this regards adding the `scope` attribute for the Global CSS CX, that PR was approved by devtool already ([see](https://github.com/liferay-devtools/liferay-portal/pull/314)). Sending here to speed things up, Evan is off until next week. 

----

https://liferay.atlassian.net/browse/LPD-37520

## Goal

To inject GlobalCSSCETs that are scoped to the company

## Approach

In `ClientExtensionTopHeadDynamicInclude.java`, import the GlobalCSSCETs CSS url that have `company` as value for the `scope` attribute. This import is not conditional, once the company scoped GlobalCSSCETs is deployed to portal, it's going to be imported (since the feature flag is enabled).

### Up next

I will be adding the sample and functional tests. See https://liferay.atlassian.net/browse/LPD-43551

cc: @ethib137

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:gradle-plugins

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:gradle-plugins

**Comment by thiago-buarqque** [comment]
@drewbrokke `gradle-plugins` suite is failing due to unrelated error, can I forward this one?

**Review by drewbrokke — APPROVED** [review]
@thiago-buarqque this seems ok to me, are there any other component owners that need to approve this?

**Comment by thiago-buarqque** [comment]
@drewbrokke No, thanks Drew :)

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:gradle-plugins

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:forward

**Pull request closed without merging**
