### PR TITLE
Nicolas - SF Automation - master lpd 31260

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-31260
@nicolas-sss I cant assign you but here is one of the PRs

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:hotel

**Comment by nicolas-sss** [comment]
@kyle-miho Good work!
I have one question regarding this pattern. Do other DTO converters exhibit similar behavior? If so, it might be beneficial to generalize this check to handle all potential cases.

Maybe use a list of all cases and a more generic regular expression to capture various scenarios. This would help consolidate multiple checks into a single location, reducing the need for additional classes, test files, and code duplication.

Alternatively, within UpgradeCatchAll, if feasible, exploring the possibility of a more generalized approach could also be valuable.

Let's proceed with this PR. Please do a quick search, if you encounter other cases, please create a ticket to address this check in the future.

What do you think?

**Review by nicolas-sss — APPROVED** [review]

**Comment by kyle-miho** [comment]
@nicolas-sss Done: https://liferay.atlassian.net/browse/LPD-35708 This was not generalized because I just followed the ticket, I'll double check as I work on tickets to confirm if i can generalize in the future though.

Pushed manually here https://github.com/brianchandotcom/liferay-portal/pull/153949

**Pull request closed without merging**
