### PR TITLE
LPD-20860 Investigate test failure ClientExtensionSamples Favicon

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPD-20860](https://liferay.atlassian.net/browse/LPD-20860).
This is an update for [LPD-20854](https://liferay.atlassian.net/browse/LPD-20854).

/cc @john-co

### CODE REVIEW

**Comment by drewbrokke** [comment]
FYI @izaera

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:help

**Comment by drewbrokke** [comment]
ci:test:liferay-sample-workspace

**Comment by drewbrokke** [comment]
ci:forward:force

**Comment by izaera** [comment]
@drewbrokke Thanks. That failing test went unnoticed because there are several tests that are currently failing for the Workspace+CXs and they are going to be moved to Playwright -> https://liferay.atlassian.net/browse/LPD-19057

**Pull request closed without merging**
