### PR TITLE
LPD-24834 [client-extensions] add support for local deployment of CX bundles to different virtual instances

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPD-24834](https://liferay.atlassian.net/browse/LPD-24834).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@annasuszter would you be willing to test these changes to make sure they are still working as expected?

Also, I see an opportunity for some test updates, particularly in `ArtifactURLUtilTest`.

**Comment by annasuszter** [comment]
New PR: #148

**Pull request closed without merging**
