### PR TITLE
LPS-202509 Dev Workspace: Add a substitution variable containing the build time that can be used in CX URLs

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-202509](https://issues.liferay.com/browse/LPS-202509).

The intent of this pull request is to allow query parameters in wildcard urls. It is a generic solution that is not limited to the proposed variables such as `t=${modifiedTimestamp}`, but that is supported. With this change, it is now possible to use this syntax: 

```yaml
urls:
  - *.js?t=${modifiedTimestamp}
  - *.css?t=${modifiedTimestamp}
```

It should be noted that now that Ray's PR [adding the buildTimestamp](https://github.com/liferay-devtools/liferay-portal/pull/11/commits/105f1a638c21e3b8641ef932f79b5cf13a3ee883) has been merged, the "native" configuration interpolation will also work with this syntax:

```yaml
urls:
  - *.js?t=$[conf:buildTimestamp]
  - *.css?t=$[conf:buildTimestamp]
```

This avoids the need for any special logic on the DXP side since ConfigurationAdmin will handle the substitution automatically for _any_ configuration key.

@rotty3000 please correct any points that I may have gotten wrong here.

FYI @izaera

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Review by rotty3000 — APPROVED** [review]
LGTM

**Comment by drewbrokke** [comment]
The gradle plugins failure is common in other pulls.

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
