### PR TITLE
LPD-30952 Remove incorrectly upgraded import since only some of the constants got moved to CommerceOrderPaymentConstants not all of them

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-30952
Only need to update the imports.txt file, since the upgrades already exist in the replacements.json, we just need to remove the un-needed import upgrade as it breaks compile for usages of CommerceOrderConstants

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:hotel

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:report:11580358

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@drewbrokke sf failure unrelated

**Review by drewbrokke — APPROVED** [review]

**Pull request closed without merging**
