### PR TITLE
LPD-22405 Merge the user-defined LCP.json with the default template

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPD-22405](https://liferay.atlassian.net/browse/LPD-22405).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Tested this version locally with all the workspaces, there were a couple of errors but it was either from Node or a JDK issue, neither of them were related to workspace this time.

**Comment by drewbrokke** [comment]
FYI @rotty3000 @gamerson @brianchandotcom

**Comment by drewbrokke** [comment]
SF failure is not in the workspace module. Locally SF passes.

**Comment by brianchandotcom** [comment]
@drewbrokke merged to master

**Pull request closed without merging**
