### PR TITLE
master lpd 28836

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-28836
cc: @drewbrokke @nicolas-sss

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:hotel

**Comment by kyle-miho** [comment]
ci:test:sf

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:report:20558276

**Comment by kyle-miho** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/151599

**Pull request closed without merging**
