### PR TITLE
LPS-193787 As a frontend developer trying to build using node, I want workspace to be configured to use the latest LTS version

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-193787](https://issues.liferay.com/browse/LPS-193787).

### CODE REVIEW

**Comment by drewbrokke** [comment]
FYI @simonjhy this applies the changes in just workspace using the property `liferay.workspace.node.lts.codename`. Please look over the changes when you have a chance and let me know if you have any questions or concerns.

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
> FYI @simonjhy this applies the changes in just workspace using the property `liferay.workspace.node.lts.codename`. Please look over the changes when you have a chance and let me know if you have any questions or concerns.

@drewbrokke OK thanks.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
See https://github.com/liferay-devtools/liferay-portal/pull/22

**Pull request closed without merging**
