### PR TITLE
LPS-206278 InitBundle task of Workspace plugin should not delete tomcat folder for portal quarter release

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-206278](https://issues.liferay.com/browse/LPS-206278).

@simonjhy

### CODE REVIEW

**Comment by drewbrokke** [comment]
@simonjhy would you be willing to give this one a look and verify whether it fixes the issue you've identified? Thanks!

**Comment by simonjhy** [comment]
> @simonjhy would you be willing to give this one a look and verify whether it fixes the issue you've identified? Thanks!

sure, I have started to check it. Thanks Drew

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
@drewbrokke its ok now, I tested it in local by execute gradle initBundle task and start bundle test for dxp-2023.q4.2.

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:forward:force

**Comment by drewbrokke** [comment]
ci:forward:force

**Pull request closed without merging**
