### PR TITLE
LPD-19346 Workspace leaves artifacts from previous client extension builds

### PR DESCRIPTION
**Pull request by annasuszter**
@drewbrokke, I updated the implementation based on your comments on #154

### CODE REVIEW

**Comment by annasuszter** [comment]
ci:test:sf

**Comment by annasuszter** [comment]
ci:test:relevant

**Comment by annasuszter** [comment]
ci:test:gradle-plugins

**Comment by annasuszter** [comment]
ci:test:workspaces

**Comment by drewbrokke** [comment]
See https://github.com/liferay-devtools/liferay-portal/pull/159

**Pull request closed without merging**
