### PR TITLE
Nicolas - SF Automation - Master - LPD-36648

### PR DESCRIPTION
**Pull request by MicaelleSilvaa**
Ticket: https://liferay.atlassian.net/browse/LPD-36648

### CODE REVIEW

**Comment by MicaelleSilvaa** [comment]
@nicolas-sss

**Comment by MicaelleSilvaa** [comment]
ci:test:sf

**Comment by MicaelleSilvaa** [comment]
ci:test:hotel

**Review by nicolas-sss — CHANGES_REQUESTED** [review]
Adjust as we have discussed offline.

**Pull request closed without merging**
