### PR TITLE
master lpd 30941

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-30941

cc: @drewbrokke @nicolas-sss
FYI Drew I am copying over the joinLines helper function you made for one of the previous automation tasks, I was wondering if it was better to just move it to BaseUpgradeCheck instead? so its easier to reuse?

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:hotel

**Review by drewbrokke — COMMENTED** [review]
@kyle-miho go ahead and move the `joinLines` helper to the `BaseUpgradeCheck`, it's generally useful enough.

**Comment by kyle-miho** [comment]
@drewbrokke I added it here: https://github.com/liferay-devtools/liferay-portal/pull/129/commits/ec7c8adb8134c46fd55ea0943ea462a3a66930d3
Ill create a task to refactor the rest of the upgrade checks to use the helper function in BaseUpgrade instead of their own then

**Comment by kyle-miho** [comment]
ci:help

**Review by drewbrokke — APPROVED** [review]

**Comment by kyle-miho** [comment]
@drewbrokke I'll move forward with this one, I have a task to refactor all the join lines at once

**Comment by kyle-miho** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/152471

**Pull request closed without merging**
