### PR TITLE
Nicolas - SF Automation - Master - LPD-36646

### PR DESCRIPTION
**Pull request by MicaelleSilvaa**
Ticket: https://liferay.atlassian.net/browse/LPD-36646

### CODE REVIEW

**Comment by MicaelleSilvaa** [comment]
ci:test:hotel

**Comment by MicaelleSilvaa** [comment]
ci:test:sf

**Comment by MicaelleSilvaa** [comment]
@nicolas-sss

**Review by nicolas-sss — APPROVED** [review]

**Comment by nicolas-sss** [comment]
@MicaelleSilvaa approved but must wait for the previous one to be merged before sending. This way the commits will be skipped on this pr leaving only two.

**Comment by MicaelleSilvaa** [comment]
forward to Brian: https://github.com/brianchandotcom/liferay-portal/pull/154551

**Pull request closed without merging**
