### PR TITLE
LPS-25198 Enforce the usage of FeatureFlagManagerUtil.isEnabled over _featureFlagManager.isEnabled

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://liferay.atlassian.net/browse/LPD-25198

/cc @drewbrokke

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
Thanks @ling-alan-huang!

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
