### PR TITLE
LPD-37082 Allow the rest-builder Project Template to support the quarterly templates in its declared version ranges

### PR DESCRIPTION
**Pull request by annasuszter**
[LPD-37082](https://liferay.atlassian.net/browse/LPD-37082)

### CODE REVIEW

**Comment by annasuszter** [comment]
ci:test:sf

**Comment by annasuszter** [comment]
ci:test:project-templates

**Comment by annasuszter** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@annasuszter I do not think the Project Templates failure is related in this case. We can forward it.

**Comment by annasuszter** [comment]
ci:forward

**Pull request closed without merging**
