### PR TITLE
LPD-27101 Work for Service classes needs to add @Component and register the tag service

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://liferay.atlassian.net/browse/LPD-27101

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:hotel

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:hotel

**Comment by kyle-miho** [comment]
@ling-alan-huang everything passed now, I assume its good to go?

**Pull request closed without merging**
