### PR TITLE
master lpp 55622

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-37610

### CODE REVIEW

**Comment by kyle-miho** [comment]
@drewbrokke I tested this by
1) running the unit test, see commits for the updated unit test I tested on: ProjectTemplatesFormFieldWorkspaceReactTest
2) Did a chain of updates , partially referring to the confluence document to aid in updating the blade create template, form field. I had an issue publishing to the local m2 cache (for some reason it does nothing but says successful). I did a workaround by grabbing the jar from the m2 folder and putting it into libs folder).
3) Tested on the customer's reproduceable version before and after the fix, to confirm the reproduction of the issue and that the fix prevents the issue.

I removed the TEMP-GRADLE cache commits and then kept everything else. I'm not sure if I did everything right, but I double checked and it looks good to me?

**Comment by kyle-miho** [comment]
ci:test:dev-tools

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
Updated only commit news so ticket number references the LPD not LPP

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
