### PR TITLE
LPD 6610 validate frontend token definition file existence

### PR DESCRIPTION
**Pull request by algobob**
It validates the existence of the frontend token definition json file when provided through themeCSS client extension. It also check if the file contains a valid json content.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
Resolved conflicts, performed some SF and resent to #38.

@algobob please make sure everything is okay

**Comment by thiago-buarqque** [comment]
ci:close

**Pull request closed without merging**
