### PR TITLE
LPD-25246 Change constructors to private - account

### PR DESCRIPTION
**Pull request by ling-alan-huang**
@drewbrokke I just make changes on `account` module, can you take a look to see if I did the correct changes?
Thanks.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
LGTM, thanks @ling-alan-huang!

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
