### PR TITLE
LPD-7009 read and validate script element attributes from .yaml file for deployed client extension

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Ticket: https://liferay.atlassian.net/browse/LPD-7009

Coming from liferay-platform-experience [#508](https://github.com/liferay-platform-experience/liferay-portal/pull/508)

cc: @ethib137

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:gradle-plugins

**Comment by thiago-buarqque** [comment]
ci:reevaluate:1367401_5454

**Comment by thiago-buarqque** [comment]
ci:test:gradle-plugins

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
See https://github.com/liferay-devtools/liferay-portal/pull/40

**Pull request closed without merging**
