### PR TITLE
Nicolas - SF Automation - Master LPD-36121

### PR DESCRIPTION
**Pull request by MicaelleSilvaa**
Ticket: https://liferay.atlassian.net/browse/LPD-36121

### CODE REVIEW

**Comment by MicaelleSilvaa** [comment]
@nicolas-sss

**Comment by MicaelleSilvaa** [comment]
ci:test:sf

**Comment by MicaelleSilvaa** [comment]
ci:test:hotel

**Review by nicolas-sss — APPROVED** [review]

**Comment by MicaelleSilvaa** [comment]
forward to brian: https://github.com/brianchandotcom/liferay-portal/pull/154146

**Pull request closed without merging**
