### PR TITLE
master lpd 28356

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-28356
cc: @drewbrokke @nicolas-sss

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:hotel

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:help

**Comment by kyle-miho** [comment]
ci:test:reports

**Comment by kyle-miho** [comment]
ci:report

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
Manually forwarding since SF failures are unrelated

**Comment by kyle-miho** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/151560

**Pull request closed without merging**
