### PR TITLE
LPD-22405 Merge the user-defined LCP.json with the default template

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPD-22405](https://liferay.atlassian.net/browse/LPD-22405).

FYI @rotty3000

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:help

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/148935

**Comment by brianchandotcom** [comment]
@drewbrokke I merged this to master to unblock.

**Pull request closed without merging**
