### PR TITLE
LPD-22405 Merge the user-defined LCP.json with the default template

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPD-22405](https://liferay.atlassian.net/browse/LPD-22405).

FYI @MumenTayyem

### CODE REVIEW

**Comment by drewbrokke** [comment]
FYI @rotty3000 @gamerson

**Review by rotty3000 — APPROVED** [review]
LGTM

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
