### PR TITLE
LPD-27625 Add new import cases to imports.txt

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-27625

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:hotel

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@drewbrokke this should just take a quick look, just updating the imports.txt file with new import changes

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
@kyle-miho LGTM 👍

**Comment by kyle-miho** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/154157

**Pull request closed without merging**
