### PR TITLE
LPD-24834 [client-extensions] add support for local deployment of CX bundles to different virtual instances + LPD-33601

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPD-24834](https://liferay.atlassian.net/browse/LPD-24834).

FYI @annasuszter:

One new piece of logic/functionality:
- If there is an `LCP.json` file with `dependencies` present, those will be suffixed as well when they are put into the `plugin-package.properties` file since they refer to _other_ bundle symbolic names from other client extensions.

Other adjustments are:
- Moves the suffix logic to StringUtil
- Only uses "default" where it's needed rather than checking for it in the helper method
- If both the client extension `dxp.lxc.liferay.com.virtualInstanceId` property and the `iferay.virtual.instance.id` Gradle property are set, the Gradle property will win, and we print a message indicating so.

---

This is an update for [LPD-33601](https://liferay.atlassian.net/browse/LPD-33601).

FYI @natocesarrego there are two commits in this pull for the repository ordering issue we discussed yesterday.

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
@gamerson would you be willing to give this one another look? Thanks!

**Review by gamerson — APPROVED** [review]
LGTM!

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:workspaces

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:workspaces

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:project-templates

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:project-templates

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
