### PR TITLE
LPD-37047 [SF] Consistency for string attributes in *.yaml

### PR DESCRIPTION
**Pull request by annasuszter**
This is an update for [LPD-37047](https://liferay.atlassian.net/browse/LPD-37047)

The regex matches string values inside single- or double-quotes where the string value only contains numbers, letters and spaces,  but it doesn't consist exclusively of numbers or valid boolean values (case-insensitive) and doesn't contain any special characters.

Source formatter removes the quotes from the matching strings.

@ling-alan-huang Can you please review my changes? Thank you! 

cc @drewbrokke

### CODE REVIEW

**Comment by annasuszter** [comment]
ci:test:sf

**Comment by annasuszter** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
Thank you @annasuszter 

Looks like we can remove the quotes if the string contains special characters.
Please see: `url: https://commerce.{environment}.liferay.com/commerce-admin-pricing/{basePath}` in [here](https://github.com/liferay/liferay-portal/blob/1d812550bf00975c9ad5830b8acb959e9ea70714/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-pricing-impl/rest-openapi.yaml#L4987).

Can we remove the quotes if it doesn't contain the escape character, like backslash?
Let me know what you think, thanks.

@drewbrokke  Do you have any experience in *yaml?

**Comment by annasuszter** [comment]
I'm closing this PR for now as the case requires more assesment. Unfortunately the usage of quotes in YAML string values is not straightforward, multiple versions can be correct and we need to decide which version we want to stick to.

**Pull request closed without merging**
