### PR TITLE
master lpd 28714

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-28714

cc: @drewbrokke @nicolas-sss

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:hotel

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
LGTM, we just need the tests to pass? @kyle-miho Are the failures related?

**Comment by kyle-miho** [comment]
investigating

**Comment by kyle-miho** [comment]
ci:test:hotel

**Comment by kyle-miho** [comment]
@drewbrokke fyi test failures were unrelated, im forwarding it since it passed your review and i just rebased it

**Comment by kyle-miho** [comment]
forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/151617

**Pull request closed without merging**
