### PR TITLE
LPD-36494 Removing the need to have the `lang` folder

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Previous PR https://github.com/brianchandotcom/liferay-portal/pull/154930

This change was request by Brian based on this PR https://github.com/brianchandotcom/liferay-portal/pull/154930

-------

## Original description

# Goal
To provide the ability of importing translations in PaaS/SaaS using batch client extensions. 

# Approach
Convert `Language*.properties` files to a valid batch engine file (batch-engine-data.json) so it can be easily imported using the batch framework.

As a suggestion from Marco Leo, we are not asking the user to create a client extension-like folder (i.e. adding the `client-extension.yaml` file). We are expecting a `Language.properties` file to be inside the `${workspace-root}/language` folder.

#### `buildLang`

We're also providing the ability to run the `buildLang` task to help copying the translations to different languages.

# Example

Language.properties
```properties
sample-language-key=Sample Language Value
```

Run `gw buildLang`. The output will be 

```bash
{root}
├── language
│   ├── Language_ar.properties
│    ...
│   ├── Language_nb.properties
│   ├── Language_nl_BE.properties
│   ├── Language_nl.properties
│   ├── Language_pl.properties
│   ├── Language.properties
│   ├── Language_pt_BR.properties
│   ├── Language_pt_PT.properties
│    ...
│   ├── Language_ro.properties
│   ├── Language_ru.properties
```

Run `gw deploy` and you get a zip file in a batch client extension format. The important stuff is `build/liferay-client-extension-build/batch/language.batch-engine-data.json`

```json
{
    "configuration": {
        "className": "com.liferay.portal.language.rest.dto.v1_0.Message",
        "parameters": {
            "containsHeaders": "true",
            "importStrategy": "ON_ERROR_FAIL",
            "updateStrategy": "UPDATE"
        },
        "taskItemDelegateName": "DEFAULT"
    },
    "items": [
        {
            "key": "sample-language-key",
            "languageId": "en",
            "value": "Sample Language Value"
        }
    ]
}
```

Notes regarding the generated batch file:

1. The buildLang task generates translations in fallback languages (en, fr, nl, es). But we are safe to consider, per example, `en` as `en_US` (see why [here](https://liferay.slack.com/archives/C03LW8NUK/p1726692063600729));
2. Automatic translations, the ones marked with ` (Automatic Copy)` at the end, are ignored;
3. The `buildLang` task also runs when running `gw deploy`.
4. Translations changed by the user, i.e. the ones that no longer have the suffix ` (Automatic Copy)`, will be kept untouched when running `buildLang` again

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:gradle-plugins

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
This PR has verbal approval from @petershin

**Review by drewbrokke — APPROVED** [review]

**Comment by thiago-buarqque** [comment]
ci:forward

**Pull request closed without merging**
