### PR TITLE
Nicolas - SF Automation - Master LPD-35890

### PR DESCRIPTION
**Pull request by rubenssoares-br**
Ticket - https://liferay.atlassian.net/browse/LPD-35890
@nicolas-sss

### CODE REVIEW

**Comment by rubenssoares-br** [comment]
ci:test:hotel

**Comment by rubenssoares-br** [comment]
ci:test:sf

**Comment by rubenssoares-br** [comment]
ci:test:sf

**Comment by rubenssoares-br** [comment]
ci:test:hotel

**Review by nicolas-sss — APPROVED** [review]

**Comment by nicolas-sss** [comment]
ci:test:hotel

**Comment by rubenssoares-br** [comment]
PR sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/154122

**Pull request closed without merging**
