### PR TITLE
Nicolas - SF Automation - Master LPD-35650

### PR DESCRIPTION
**Pull request by RenanUmV**
Issue: [LPD-35650](https://liferay.atlassian.net/browse/LPD-35650)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:hotel

**Review by nicolas-sss — APPROVED** [review]

**Comment by nicolas-sss** [comment]
@RenanUmV since it's been so long, remember the workflow, do a rebase, and rerun the tests (at least locally) before forwarding.
Something someone else might have added could change the order of something you've added in those files.
;)
Also, we usually send the changes made in the code and any new tests in different commits. Please, adjust that.

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:hotel

**Comment by RenanUmV** [comment]
ci:test:hotel

**Review by nicolas-sss — APPROVED** [review]

**Pull request closed without merging**
