### PR TITLE
LPS-42601 Add parameterized unit tests over from replacements.json

### PR DESCRIPTION
**Pull request by kyle-miho**
cc: @nicolas-sss @drewbrokke 
Part 1
Also fixes an issue where we run the tests sometimes a duplicate amount of times

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:hotel

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
See https://github.com/liferay-devtools/liferay-portal/pull/307

**Pull request closed without merging**
