### PR TITLE
LPD-21814 Support Gradle 8 in Workspace

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPD-21814](https://liferay.atlassian.net/browse/LPD-21814).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:workspaces:nocompile

**Comment by drewbrokke** [comment]
@kenjiheigel I just ran the workspaces command we discussed last week. Let me know if it's working as expected.

**Comment by drewbrokke** [comment]
@petershin would you be willing to give this one a look?

**Comment by drewbrokke** [comment]
@gamerson FYI

**Comment by petershin** [comment]
@drewbrokke - Please revert https://github.com/liferay-devtools/liferay-portal/pull/52/commits/68846bc28ef2e74ca86b28d3757bb522621a069e. It's happening bc bchan hasn't published a new version of SF yet

The CI sf test suite should be ok bc it builds the SF jar from source instead of using the latest published version

**Comment by drewbrokke** [comment]
> Please revert 68846bc. It's happening bc bchan hasn't published a new version of SF yet. The CI sf test suite should be ok bc it builds the SF jar from source instead of using the latest published version

Done, thanks!

**Comment by drewbrokke** [comment]
> For the gradle wrapper files, see the changes in drewbrokke#1587 It'll help keep the behavior of gradle consistent by standardizing the location of gradle home

Which part specifically am I looking at? Should I just use those gradle-wrapper updates instead?

**Comment by petershin** [comment]
> Which part specifically am I looking at? Should I just use those gradle-wrapper updates instead?

https://github.com/drewbrokke/liferay-portal/pull/1587/commits/c4d1c1c157d556965dc29875f091b9e44a84bbe4

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:workspaces

**Comment by drewbrokke** [comment]
Test @liferay-devtools

**Comment by drewbrokke** [comment]
ci:test:workspaces

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by petershin** [comment]
@drewbrokke - Search `project-templates` for `biz.aQute.bnd`. Those dependencies likely need to be bumped to `6.4.0` too.

**Comment by petershin** [comment]
ci:test:help

**Comment by petershin** [comment]
@drewbrokke - There's a ci test suite for `project-templates`. I think that one should be run for this pull too

**Comment by drewbrokke** [comment]
Thanks for the feedback @petershin, I'll work on those changes.

**Comment by drewbrokke** [comment]
ci:test:project-templates

**Comment by drewbrokke** [comment]
ci:test:project-templates

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
@petershin I pushed the updates. Let me know if there's anything else, otherwise I'll wait for the CI results and forward. Thanks!

**Comment by drewbrokke** [comment]
ci:test:project-templates

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:project-templates

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:project-templates

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:project-templates

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:report:2567392708

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:project-templates

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:project-templates

**Comment by drewbrokke** [comment]
ci:forward:force

**Comment by drewbrokke** [comment]
ci:forward:force

**Comment by drewbrokke** [comment]
ci:help

**Comment by drewbrokke** [comment]
ci:test:workspaces

**Pull request closed without merging**
