### PR TITLE
Nicolas - SF Automation - Master - LPD-36631

### PR DESCRIPTION
**Pull request by rubenssoares-br**
Ticket - https://liferay.atlassian.net/browse/LPD-36631
@nicolas-sss

### CODE REVIEW

**Review by nicolas-sss — APPROVED** [review]

**Comment by nicolas-sss** [comment]
@rubenssoares-br After resolving the conflict, perform a rebase, fix the issue locally, and then resend the changes. Once the changes pass the tests after the rebase of the PR is approved, you are free to proceed with forwarding.

**Comment by rubenssoares-br** [comment]
ci:test:sf

**Comment by nicolas-sss** [comment]
ci:test:hotel

**Comment by rubenssoares-br** [comment]
PR sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/154566

**Pull request closed without merging**
