### PR TITLE
master lpd 27539

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-27539
cc: @drewbrokke @nicolas-sss

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]
Looks good, thanks @kyle-miho!

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:hotel

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by nicolas-sss** [comment]
LGTM 👍🏻

**Review by nicolas-sss — APPROVED** [review]

**Comment by kyle-miho** [comment]
rebased commits, no actual changes

**Comment by kyle-miho** [comment]
ci:forward:force

**Comment by kyle-miho** [comment]
ci:forward:force

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/151376

**Pull request closed without merging**
