### PR TITLE
LPD-25678 New tag format for releases caused bug in some automations

### PR DESCRIPTION
**Pull request by ling-alan-huang**
@michaelmdelcavalcanti

> **Context:** For the source formatter to apply some automations, it is necessary to create a file called source-formatter.properties in the customer's workspace Liferay and add a property that points to the new version that the workspace will receive, this property was called upgrade.to.version. The change in the format in which the release tag was defined caused some automations to stop working correctly. Previously a tag, such as `u92`, should be written in the form `7.4.13.u92`, but with the start of quarterly releases following a new format, such as `2024.q1.1`, this standard needed to be revised. Some automations require the tag to have the old format, while others require the tag to be in the new format. Therefore, it was understood that this tag would need to be divided, one to meet the old standard and one to meet the new standard, for the old standard a tag called upgrade.to.liferay.version was made, for the new standard a tag called upgrade.to.release.version was made, and then after creating the new tags the automations had their tags replaced according to their behavior.
> 
> **Note**: In general, the tag in the old format does not need to specify the exact release, the most important part being `7.4`, so leaving the tag written without specifying the release does not cause problems with automation, and it is suggested to use the tag as `7.4.13.u` or just `7.4`.
> 
> For more information, see the issue: [LPD-25678](https://liferay.atlassian.net/browse/LPD-25678)

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@michaelmdelcavalcanti Who was able to review upgrade changes on Upgrade in SF module before?
/cc @drewbrokke

**Comment by michaelmdelcavalcanti** [comment]
> @michaelmdelcavalcanti Who was able to review upgrade changes in SF module before? /cc @drewbrokke

Hello @ling-alan-huang.
Previously, SF changes related to upgrade automation were reviewed by @nicolas-sss and @natocesarrego and after approval, they could be sent to @brianchandotcom, right now the process changed and the devtools team is responsible for reviewing these changes.

**Comment by ling-alan-huang** [comment]
Thanks @michaelmdelcavalcanti 
Can you let me know why some of checks only use `UPGRADE_TO_LIFERAY_VERSION`, and some checks use `UPGRADE_TO_RELEASE_VERSION`.

**Comment by michaelmdelcavalcanti** [comment]
Of course.

For `UPGRADE_TO_RELEASE_VERSION` `2024.q1.1`:

`GradleUpgradeReleaseDXPCheck` needs to request the https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/portal/release.dxp.bom/ URL to check the release version.

`JSPUpgradeRemovedTagsCheck`, `UpgradeDeprecatedAPICheck`, and `UpgradeRemovedAPICheck`  are checks that inform about deprecated or non-existent things in the defined version. I believe that the release tag should be used in these messages because it is more specific.

For `UPGRADE_TO_LIFERAY_VERSION` `7.4.13.u92`:

`PropertiesUpgradeLiferayPluginPackageFileCheck` and `PropertiesUpgradeLiferayPluginPackageLiferayVersionsCheck` need to check the 
liferay-plugin-package.properties file with the code block:
`liferay-versions=7.4.0+`

`XMLUpgradeCompatibilityVersionCheck` needs to check the files with the following code block:
```
<compatibility>
	<version>7.4.0+</version>
</compatibility>
```
`XMLUpgradeDTDVersionCheck` and `XMLUpgradeRemovedDefinitionsCheck` need to check the files with the following code block:
`<!DOCTYPE service-builder PUBLIC "-//Liferay//DTD Service Builder 7.4.0//EN" "http://www.liferay.com/dtd/liferay-service-builder_7_4_0.dtd">`

**Comment by ling-alan-huang** [comment]
Thanks @michaelmdelcavalcanti 
@drewbrokke Any one can do the further reviewing in our team?

**Comment by drewbrokke** [comment]
@ling-alan-huang if this looks ok to you, then I'm ok to forward.

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
