### PR TITLE
Nicolas - SF Automation - master lpd 29804

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-29804
@nicolas-sss this is the third PR

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:hotel

**Review by nicolas-sss — APPROVED** [review]

**Comment by nicolas-sss** [comment]
Manually forwarded [here](https://github.com/brianchandotcom/liferay-portal/pull/153897)

**Comment by nicolas-sss** [comment]
@kyle-miho can close this PR now, thx.

**Pull request closed without merging**
