### PR TITLE
master lpd 33272

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LPD-33272

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:dev-tools

**Comment by kyle-miho** [comment]
ci:test:dev-tools

**Comment by kyle-miho** [comment]
ci:help

**Comment by kyle-miho** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
See https://github.com/liferay-devtools/liferay-portal/pull/164

**Pull request closed without merging**
