### PR TITLE
LPD-40131 Use dependsOn insetad of finalizedBy to fix frontend tasks build order

### PR DESCRIPTION
**Pull request by kyle-miho**
Forwarded from: https://github.com/liferay-devtools/liferay-portal/pull/281
cc: @drewbrokke @annasuszter 

https://liferay.atlassian.net/browse/LPD-40131
https://liferay.atlassian.net/browse/LPP-56189

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:dev-tools

**Comment by kyle-miho** [comment]
ci:test:gradle-plugins

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@kyle-miho please add a test case to reproduce the bug. See https://github.com/liferay-devtools/liferay-portal/pull/281#pullrequestreview-2402907938.

**Comment by drewbrokke** [comment]
See https://github.com/liferay-devtools/liferay-portal/pull/299

**Pull request closed without merging**
