### PR TITLE
Nicolas - SF Automation - Master-LPD-37503

### PR DESCRIPTION
**Pull request by rubenssoares-br**
Ticket - https://liferay.atlassian.net/browse/LPD-37503
@nicolas-sss

### CODE REVIEW

**Comment by rubenssoares-br** [comment]
ci:test:sf

**Comment by rubenssoares-br** [comment]
ci:test:hotel

**Comment by rubenssoares-br** [comment]
ci:test:sf

**Review by nicolas-sss — APPROVED** [review]

**Comment by rubenssoares-br** [comment]
PR sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/154639

**Pull request closed without merging**
